---
title: "Quercus pyrenaica review"
author: "AJ Perez-Luque (`@ajpelu`)"
date: "` r Sys.Date()`"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: ./aux_files/references.bib
csl: ./aux_files/ecology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Para estudios relacionados con Sierra Nevada le añadiremos el símbolo :round_pushpin: 

# Taxonomía 

En su obra *Rariorum aliquot stirpium per Hispanias observatarum historia: libris duobus expressa* el autor francés Clusius (Charles de L'Ecluse) hace referencia al melojo como Robur II presentándo un dibujo de esta especie. 

* Respecto a la taxonomía, [Denk et al. 2017](https://doi.org/10.6084/m9.figshare.5547622.v1) proporcionan una exahustiva revisión de las diferentes clasifiaciones taxonómicas de las especies de Quercus. 

# Xylem structure 

## Wood density 
* 0.84 (g/cm^3) [@Zanne2009; @Chave2009] Wood density (g/cm^3), oven dry mass/fresh volume


# Revisión estudios Q. pyrenaica 

## Estación de Crecimiento

* Esta especie tiene una estación de crecimiento corta, desde el final de Mayo hasta mitad de Octubre [@Moreno2011] 

## Fenología de la formación de la madera

En un estudio en Valsain @FernandezUna2017 donde se analizó la fenología de la producción de madera (cambial phenology) en un tratamiento de exclusión de lluvia y otro control, encontró los siguientes resultados:

* Earlywood (EW) se forma entre final de Marzo y principios de Abril. La lignificación ocurre de entre 1 a 8 semanas después

* Latewood (LW) se forman entre Junio y mitad de Julio, siendo la lignificación 2 semanas después. 

* No se encontraron diferencias entre los tratamientos (control y exclusión de lluvía) respecto a la fenología de formación y crecimiento del xilema 

## Estructura del sistema radical

* El 50 % de la biomasa de las raices de Q. pyrenaica se encuentran en los primeros 10 cm (individuos de areal basal > 50.3 mm^2) [@Silva2003]. La parte mas densa de las raíces se encuentran entre los primeros 60 cm, y luego tiene una raiz principal que le permite al árbol alcanzar agua en las partes mas profundas del suelo. 



## Adaptaciones a la sequía

## LAI 

* Una estrategia comun para prosperar en condiciones limitantes de agua es la reducción del área de transpiración, así el LAI suele decrecer con el déficit de agua. [@Moreno2011] 

* LAI medio: 2.4 m^2 m^2 para stands en el centro-oeste de España. Este valor es bajo o muy bajo comaparado con los valores de otras especies caducifolias del género Quercus [@Moreno2011] 

## Potencial hídrico 

* Los valores de algunos parámetros hídricos en Q. pyrenaica son mas parecidos a robles perennifolios que a los que presentan robles caducifolios [@Moreno2011] 

### Evitación de la sequía 

    * Profundidad del sistema radical
    * Alta proporcion sistema radical / parte aérea 
    * Hojas gruesas 
    * Alta rapidez cierre estomas cuando se seca el aire o el suelo 

#### Profundidad sistema radical
* Raices llegan incluso hasta la capa freática
* Provocan movimiento de agua:

    * Desde zonas mas profundas hasta mas superficiales (*hydraulic lifting*) 
    * Removilización entre zonas con diferente grado de humectación dentro del mismo horizonte edáfico 

#### Inversión de biomasa en las raíces
* Los robles presentan una alta proporción biomasa subterránea:biomasa aérea en ambientes mediterráneos (1:1 a 1:5), lo cual asegura un buen abastecimiento de agua a las hojas durante el verano. 

* Las especies rebrotadoras (con mayor ratio subterraneo:aérea) muestran mejor estatus hídrico tras la actuación pero pueden mostrar problemas de suficiencia hidráulica en años secos. 

#### Cierre estomático 
* En terminos generales la regulación estomática de los robles se ajusta al de especies típicamente anisohídricas, que son capaces de mantener tasas de transpiración altas pese a una disminución del estatus hídrico general de la planta en terminos de potencial hídrico. En las isohídricas (como por ejemplo los pinos) la limitación de las pérdidas de agua están dirigidas al mantenimiento del estatus hídrico de la planta por encima de unos niveles determinados 
    
#### Otras adpatciones foliares
* Hojas esclerófilas 
* Baja relación superficie/peso (SLA *specific leaf area*)
* Cutícula gruesa

Estas adaptaciones permiten a los Quercus reducir la perdida de agua. 
    
### Tolerar la sequía 

#### Propiedades del sistema hidráulico: 

  *$\psi_{50} $ define el nivel de tensión en el xilema que da lugar a una pérdida en la capacidad de transporte de agua por embolia en los vasos de un 50 % respecto a la capacidad máxima. Es un parámetro empleado para definir la sensibilidad del sistema hidráulico frente a los fenómenos de cavitación, y por tanto de tolerancia a la sequía.  
  
  * Los Quercus se consideran relativamente resistentes a los fenomenos de cavitación dentro de las angiospermas, aunque en ambientes meditarráneos hay que matizarlo, ya que son menos resistentes que otras especies con las que conviven. 
  
#### Capacidad para mantener la turgencia y estructura celular en situaciones de déficit hídrico.

* Ajuste osmótico: Acumulación activa de moléculas de bajo peso molecular para mantener la turgencia celular bajo potenciales hídricos bajos. Así las plantas retrasan el marchitamiento de los tejidos en condiciones de sequía. Es un elemento característico de especies de Quercus típicamente mediterráneas, y también observable en otros como *Q pyrenaica*. El ajuste osmótico se concreta a nivel celular en la acumulación de compuestos con actividad osmótica: azúcares (glucosa, fructosa y sacarosa); alcoholes azucarados, amino-ácidos, quercitol (*Q. suber*, *Q. robur*) 

#### Mecanismos de disipación de energía. 
Se intenta minimizar el daño oxidativo cuando la FS y la transpiración se ven mermadas por la sequía. Para evitar el daño del exceso de energía (se capta más energía de la que se puede utilizar en la asimilación de CO2) se ponen en marchas mecanismos de disipación de la energía, como por ejemplo: 

* Variación en pigmentos. Se disipa energía en forma de calor, acoplandola al ciclo de diferentes pigmentos, como por ejemplo las xantofilas [@GarciaPlazaola2002] (*Concentración de Luteínas*: 4.98 ± 0.20 mmol Lx (Luteín-epoxide) / mol (Chl a+b) [@GarciaPlazaola2002])

* Síntesis de compuestos antioxidantes: compuestos orgánicos volátiles

#### Interacciones de la sequía con otros factores ecológicos
##### Luz 

* Un ambiente sombreado es el mas favorable para los Quercus a edades tempranas (mayor contenido hidrico en el suelo, mas capacidad fisiológica para hacer frente a la sequía)

# Efectos de la sequía en Q. pyrenaica

## Cambium 

* En un experimento de exclusión de lluvia (sequía) durante tres años no se observaron diferencias en el número de células del cambium entre el tratamiento control y el de exclusión de lluvia [@FernandezUna2017] 

## Crecimiento de la madera 

* Las tasas de crecimiento de la madera (tanto la temprana *EW* como la tardía *LW*) no fueron diferentes entre tratamientos (sequía y control) [@FernandezUna2017]. No obstante para el tratamiento de exclusión de lluvia se observó una tendencia decreciente en la tasa de crecimiento de LW durante el tiempo que duró el experimento [@FernandezUna2017] ($IDEA$ Efecto acumulativo??)

## Hydraulic features 

* El diámetro de los vasos EW no mostró diferencias entre tratamientos ni entre años [@FernandezUna2017]. $OJO$ otros estudios encontraron aumento o disminución (ver [@FernandezUna2017])

* Varios estudios coinciden en que bajo condiciones de sequía (exclusión de lluvia) el *Q. pyrenaica* sufren una reducción mayor conforme pasan los años sin lluvia en la anchura de los vasos LW. Este hipotético efecto acumulativo de la exclusión de lluvia es más evidente en especies de anillo poroso debido a la alta dependencia en estas especies de los carbohidratos almacenados para formar sus anillos anuales

* Bajo condiciones de exclusión de lluvia, Q. pyrenaica, mantiene el tamaño de los vasos EW, sin embargo reduce la anchura de los vasos LW 




## Fisiología 

### Potencial hídrico foliar

[@MartinezVilalta2014] proponen una aproximación conceptual para el transporte de agua en plantas y realizan una revisión bibliográfica sobre potenciales hídricos bajo condiciones de estrés. Su modelo ofrece los siguientes valores para *Qp* (utilizando valores ofrecidos en el paper de [@RodriguezCalcerrada2007])

* Potencial hídrico foliar antes del amanecer (*Predawn leaf water potential*; *c* soil water potential): slope: 0.711 
* Potencial hídrico foliar a mediodía  (*Midday leaf water potential*; *c* minimum leaf water potential): -1.485 

## References 